In [22]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd
import numpy as np

In [3]:
# label 인코딩 
# 주의: 회기모델을 만들때, 데이터를 이렇게 만들면 만드는 과정에서 문제가 생긴다.
# 냉장고에 에어컨을 더하면 전자레인지? 말이 안된다.. 크기순서같은 것도 없다.
# 레이블 인코딩을 할때는 0부터 시작해서 일련번호를 붙여준다. 데이터가 발생되는 순서대로 0부터 쭉 번호를 붙여준다.
# 문자열데이터를 숫자로 변환할때 사용하는 것이다.
# 주의!!! 레이블 인코딩은 선형회귀와 같은 알고리즘에 적용하면 안됨!!!
# - 숫자간의 대소관계를 따지기 때문임.!!

items=['tv', '냉장고', '에어컨','에어컨','전자레인지']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print(labels)

[0 1 2 2 3]


In [4]:
encoder.inverse_transform(labels) #원 데이터

array(['tv', '냉장고', '에어컨', '에어컨', '전자레인지'], dtype='<U5')

In [5]:
encoder.classes_ #종류

array(['tv', '냉장고', '에어컨', '전자레인지'], dtype='<U5')

In [6]:
#OneHotEncoding
labels #레이블 인코딩이 되어져있는 상태


array([0, 1, 2, 2, 3])

In [7]:
# 1. 문자열 값을 숫자로 변환
items=['tv', '냉장고', '에어컨','에어컨','전자레인지']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print(labels)

[0 1 2 2 3]


In [13]:
# 2. 숫자로 변환된 데이터에 대해 원핫인코딩
# 1) 2차원으로 변환
labels.reshape(-1,1)

array([[0],
       [1],
       [2],
       [2],
       [3]])

In [15]:
# 2) 원핫인코딩
labels=labels.reshape(-1,1)
ohe=OneHotEncoder()
ohe.fit(labels)
oh_labels=ohe.transform(labels)
oh_labels.toarray()
#getdummies 함수도 가능

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
df=pd.DataFrame(['tv', '냉장고', '에어컨','에어컨','전자레인지','tv'], columns=['items'])

In [21]:
pd.get_dummies(df) #OneHotEncoding

items_tv  items_냉장고  items_에어컨  items_전자레인지
0         1          0          0            0
1         0          1          0            0
2         0          0          1            0
3         0          0          1            0
4         0          0          0            1
5         1          0          0            0