##### http://gutenberg.org  
- 무료 책 받는곳

- http://gutenberg.org/ebooks/6130 
- 원하는책을 찾고 utf-8로 모든 텍스트를 받을수있다.

In [1]:
import numpy as np
import urllib.request

In [2]:
#다운로드 받는법
urllib.request.urlretrieve("http://www.gutenberg.org/files/6130/6130-0.txt", filename="lliad.txt")
f = open('lliad.txt', 'rb')
lines=[]
for line in f:
    line=line.lower() # 소문자 변환
    line=line.decode('ascii', 'ignore') # acii코드의 범위를 벗어난 특수문자 제거
    if len(line) > 0:
        lines.append(line)
f.close()

In [3]:
lines[:10]

['the project gutenberg ebook of the iliad, by homer\r\n',
 '\r\n',
 'this ebook is for the use of anyone anywhere in the united states and most\r\n',
 'other parts of the world at no cost and with almost no restrictions\r\n',
 'whatsoever.  you may copy it, give it away or re-use it under the terms of\r\n',
 'the project gutenberg license included with this ebook or online at\r\n',
 "www.gutenberg.org.  if you are not located in the united states, you'll have\r\n",
 'to check the laws of the country where you are located before using this ebook.\r\n',
 '\r\n',
 'title: the iliad\r\n']

In [5]:
text=" ".join(lines)
print(len(text))

1160564


In [9]:
sorted(list(set(text)))

['\n',
 '\r',
 ' ',
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 '@',
 '[',
 ']',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [10]:
len(sorted(list(set(text))))

60

RNN -> LSTM 
- 다음 cell 층으로 갈때 기억된 값을 전달 할것인지를 관리하는 기능이 추가가 된다. (가중치)

In [14]:
from keras.models import Model
from keras.layers import Input, Dense, LSTM
import numpy as np


x = np.array([[[1.], [2.], [3.], [4.], [5.]]])
y = np.array([[6.]])


xInput = Input(batch_shape=(None, 5, 1))
xLstm = LSTM(3)(xInput) #3 차원으로 출력
xOutput = Dense(1)(xLstm) #최종적으로 1개가 출력됨


model = Model(xInput, xOutput)
model.compile(loss='mean_squared_error', optimizer='adam')

print(model.summary())


model.fit(x, y, epochs=50, batch_size=1, verbose=0)
model.predict(x, batch_size=1)


Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 5, 1)]            0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 3)                 60        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 4         
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________
None


array([[0.5961892]], dtype=float32)

In [12]:
x.shape # input_shape : (1, 5, 1)
# (데이터(샘플)개서, 시간차원(time step size), LSTM셀에 입력되는 데이터의 feature 개수)
# (None, 5, 1) : None인 이유 -> 지금은 한건이지만 내일은 추가 된다. 추가 될때 마다 1을 2,3으로 바꿀 필요가 없다.
# None으로 주면 알아서 채워넣는다.

(1, 5, 1)

# 뉴스 분류기
- reuters 통신사 뉴스기사 만개가 넘고 40개가 넘는 카테고리가 있다.

In [55]:
from keras.datasets import reuters
(xTrain,yTrain), (xTest, yTest)=reuters.load_data(num_words=1000, test_split=0.2) #가장 많이 언급된 단어 1000개를 뽑아라 / 자동으로 테스트데이터가 20퍼센트 나머지 80퍼센트 트레이닝으로 나누어 준다.

In [56]:
xTrain #특정단어
print(xTrain[0]) #첫번째 로이터 통신사 뉴스 데이터

[1, 2, 2, 8, 43, 10, 447, 5, 25, 207, 270, 5, 2, 111, 16, 369, 186, 90, 67, 7, 89, 5, 19, 102, 6, 19, 124, 15, 90, 67, 84, 22, 482, 26, 7, 48, 4, 49, 8, 864, 39, 209, 154, 6, 151, 6, 83, 11, 15, 22, 155, 11, 15, 7, 48, 9, 2, 2, 504, 6, 258, 6, 272, 11, 15, 22, 134, 44, 11, 15, 16, 8, 197, 2, 90, 67, 52, 29, 209, 30, 32, 132, 6, 109, 15, 17, 12]


In [57]:
yTrain #xTrain에 대한 뉴스 카테고리

array([ 3,  4,  3, ..., 25,  3, 25])

In [58]:
import numpy as np

In [59]:
np.min(yTrain), np.max(yTrain) #뉴스 카테고리가 0~45 = 46개의 카테고리가 있다.

(0, 45)

In [60]:
category=np.max(yTrain)+1
category

46

In [61]:
len(xTrain) #8982개 뉴스기사 (학습)
len(xTest) #2246개 뉴스기사 (테스트)

2246

In [62]:
len(xTrain[8981])

105

In [63]:
from keras.preprocessing import sequence

In [64]:
xTrain=sequence.pad_sequences(xTrain, maxlen=100) #단어 개수가 100이 넘어가면 넘는 단어들은 잘린다.
xTest=sequence.pad_sequences(xTest, maxlen=100)

In [65]:
xTrain[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         1,   2,   2,   8,  43,  10, 447,   5,  25, 207, 270,   5,   2,
       111,  16, 369, 186,  90,  67,   7,  89,   5,  19, 102,   6,  19,
       124,  15,  90,  67,  84,  22, 482,  26,   7,  48,   4,  49,   8,
       864,  39, 209, 154,   6, 151,   6,  83,  11,  15,  22, 155,  11,
        15,   7,  48,   9,   2,   2, 504,   6, 258,   6, 272,  11,  15,
        22, 134,  44,  11,  15,  16,   8, 197,   2,  90,  67,  52,  29,
       209,  30,  32, 132,   6, 109,  15,  17,  12], dtype=int32)

In [66]:
from keras.utils import to_categorical

In [67]:
yTrain=to_categorical(yTrain) #어떤 카테고리에 속하는지 원핫인코딩 (꼭 해야한다.) 범주형으로 만들어 주어야한다. 그렇지 않으면 0+1=>????
yTest= to_categorical(yTest)

In [68]:
yTrain, yTest

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))

In [69]:
from keras.layers import Embedding, LSTM, Dense
from keras.models import *
from keras.callbacks import *
from datetime import datetime
from sklearn.preprocessing import MinMaxScaler

In [70]:
model=Sequential()
model.add(Embedding(1000, 100)) #[001000000...00000] => [0.2, 0.5, -0.1...0.7]
#Embedding(불로온 단어의 총 개수, 축소된 차원)
model.add(LSTM(100, activation='tanh'))
model.add(Dense(46, activation='softmax'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, None, 100)         100000    
_________________________________________________________________
lstm_7 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_6 (Dense)              (None, 46)                4646      
Total params: 185,046
Trainable params: 185,046
Non-trainable params: 0
_________________________________________________________________


In [71]:
model.compile(loss="categorical_crossentropy",
             optimizer='adam', metrics=['accuracy'])

In [72]:
history=model.fit(xTrain, yTrain, batch_size=100, epochs=30, validation_data=(xTest, yTest))

Epoch 1/30
90/90 [==============================] - 9s 103ms/step - loss: 2.6131 - accuracy: 0.3407 - val_loss: 2.3985 - val_accuracy: 0.3620
Epoch 2/30
90/90 [==============================] - 9s 100ms/step - loss: 2.1628 - accuracy: 0.4537 - val_loss: 2.0254 - val_accuracy: 0.5067
Epoch 3/30
90/90 [==============================] - 9s 100ms/step - loss: 2.0530 - accuracy: 0.4874 - val_loss: 1.8820 - val_accuracy: 0.5080
Epoch 4/30
90/90 [==============================] - 9s 100ms/step - loss: 1.7864 - accuracy: 0.5395 - val_loss: 1.7382 - val_accuracy: 0.5512
Epoch 5/30
90/90 [==============================] - 9s 100ms/step - loss: 1.6943 - accuracy: 0.5603 - val_loss: 1.7912 - val_accuracy: 0.5267
Epoch 6/30
90/90 [==============================] - 9s 100ms/step - loss: 1.6255 - accuracy: 0.5752 - val_loss: 1.6647 - val_accuracy: 0.5761
Epoch 7/30
90/90 [==============================] - 9s 101ms/step - loss: 1.5502 - accuracy: 0.5911 - val_loss: 1.5827 - val_accuracy: 0.5944
Epoch 

In [ ]:
model.predict_classes(xTest)

In [ ]:
np.argmax(yTest[2])

In [ ]:
model.save("reuters_model.h5")

In [54]:
from keras.models import load_model

In [ ]:
rmodel=load_model("reuters_model.h5")