In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pandas as pd
data=pd.read_csv("bc/data.csv")

In [2]:
data.isnull().sum()
data.isna().sum()



id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [3]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [7]:
xdata=data.iloc[:,2:32].values
xdata
ydata=data.iloc[:,1].values
ydata

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'M',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M

In [8]:
#레이블 인코더로 객체를 만듦니다
le=LabelEncoder()
ydata=le.fit_transform(ydata)
ydata

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
xtrain, xtest, ytrain, ytest=train_test_split(xdata, ydata, test_size=0.25, random_state = 0)

[3.3 scikit-learn의 전처리 기능](https://datascienceschool.net/view-notebook/f43be7d6515b48c0beb909826993c856/)

In [12]:
#표준화 (전처리) scaling
from sklearn.preprocessing import StandardScaler

In [13]:
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [14]:
xtrain

array([[-0.65079907, -0.43057322, -0.68024847, ..., -0.36433881,
         0.32349851, -0.7578486 ],
       [-0.82835341,  0.15226547, -0.82773762, ..., -1.45036679,
         0.62563098, -1.03071387],
       [ 1.68277234,  2.18977235,  1.60009756, ...,  0.72504581,
        -0.51329768, -0.96601386],
       ...,
       [-1.33114223, -0.22172269, -1.3242844 , ..., -0.98806491,
        -0.69995543, -0.12266325],
       [-1.25110186, -0.24600763, -1.28700242, ..., -1.75887319,
        -1.56206114, -1.00989735],
       [-0.74662205,  1.14066273, -0.72203706, ..., -0.2860679 ,
        -1.24094654,  0.2126516 ]])

In [15]:
xtest

array([[-0.21395901,  0.3125461 , -0.14355187, ...,  1.37043754,
         1.08911166,  1.53928319],
       [-0.26750714,  1.461224  , -0.32955207, ..., -0.84266106,
        -0.71577388, -0.88105993],
       [-0.03922298, -0.86770223, -0.10463112, ..., -0.505318  ,
        -1.20298225, -0.92494342],
       ...,
       [-0.51270124, -1.69096186, -0.54095317, ..., -0.12632201,
         0.33773512, -0.42872244],
       [-0.17732081, -2.01395163, -0.17345939, ..., -0.62875108,
        -0.29500302, -0.65432858],
       [ 1.5305829 , -0.26300709,  1.57961296, ...,  1.6694843 ,
         1.18085869,  0.48889253]])

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
rfModel=RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
rfModel.fit(xtrain,ytrain)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [18]:
ypred=rfModel.predict(xtest)

In [19]:
ypred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [21]:
cm= confusion_matrix(ytest, ypred)
cm

array([[89,  1],
       [ 1, 52]])

In [24]:
accuracy_score(ytest, ypred) # 98.6%

0.986013986013986

In [5]:
#문자 -> 숫자 : 레이블 인코딩, 원핫 인코딩

#문자열 데이터 : 카테고리형(학점,도시...) , 텍스트형(일반적인 문장에 포함된 단어들..)
#A->1, B->2, ...CDF (레이블 인코딩, 숫자가 커질수록 학점이 나쁨)
#A<B<C<D<F

#서울->1, 대전->2, 부산->3, 제주->4, 강릉->5... (레이블 인코딩을 하면 안됨->원핫인코딩)
# 1+2=>3 서울+대전=부산?? 
# 1<2<3<...???

#A->1000, B->0100, O->0010, AB->0001 (원핫인코딩)
#서울->10000, ... 강릉->00001 (원핫인코딩)

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#주의!!! 레이블 인코딩은 선형회귀와 같은 알고리즘에 적용하면 안됨!!!

In [6]:
items=['tv', '냉장고', '에어컨', '에어컨', '전자레인지', 'tv']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print(labels)

[0 1 2 2 3 0]


In [7]:
encoder.inverse_transform(labels) #원 데이터

array(['tv', '냉장고', '에어컨', '에어컨', '전자레인지', 'tv'], dtype='<U5')

In [8]:
encoder.classes_ #종류

array(['tv', '냉장고', '에어컨', '전자레인지'], dtype='<U5')

In [9]:
labels

array([0, 1, 2, 2, 3, 0])

In [10]:
#원핫인코딩: 1) 원핫인코딩을 하기 전에 모든 문자열 값을 숫자로 변환
#2) 숫자로 변환된 데이터(2차원)에 대해 원핫인코딩

In [11]:
#원핫인코딩
items=['tv', '냉장고', '에어컨', '에어컨', '전자레인지', 'tv']
#1) 원핫인코딩을 하기 전에 모든 문자열 값을 숫자로 변환
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print(labels)

#숫자로 변환된 데이터(2차원)에 대해 원핫인코딩
labels=labels.reshape(-1,1)
ohe=OneHotEncoder()
ohe.fit(labels)
oh_labels=ohe.transform(labels)
print(oh_labels.toarray())


df=pd.DataFrame(['tv', '냉장고', '에어컨', '에어컨', '전자레인지', 'tv'], 
                columns=['items'])
pd.get_dummies(df)

[0 1 2 2 3 0]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


items_tv  items_냉장고  items_에어컨  items_전자레인지
0         1          0          0            0
1         0          1          0            0
2         0          0          1            0
3         0          0          1            0
4         0          0          0            1
5         1          0          0            0

In [ ]:
#변수의 스케일링(표준화, 정규화)을 하지 않아도 됨
#연속형, 바이너리형.. 데이터들이 혼합되어 있어도 잘 동작

#유클리디안거리
#x축:몸무게, y축:태어난 날로부터 경과일(30살=약11000)
#(y2-y1)2 + (x2-x1)2   1/2
#47    10099

In [28]:
#train -> dt -> 모델 -> train입력 -> 모델평가(성능100%) => 가지치기를 안함.
#train입력-> 모델평가(95%) >> test입력->모델평가(73%) => 오버피팅(일반화를(가지치기) 하지 않아서...)