중복데이터 처리, 연관규칙 association  
set / reset index  


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
billboard=pd.read_csv('billboard.csv')
billboard

year            artist                    track  time date.entered  wk1  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87   
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91   
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08   81   
3    2000      3 Doors Down                    Loser  4:24   2000-10-21   76   
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   57   
..    ...               ...                      ...   ...          ...  ...   
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   86   
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   85   
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   95   
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   99   
316  2000   matchbox twenty                     Bent  4:12   2000-04-29   60   

      wk2   wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  \
0    82.0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1    87.0  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2    70.0  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3    76.0  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4    34.0  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
312  83.0  77.0  74.0  83.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313  83.0  83.0  82.0  81.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
314  94.0  91.0  85.0  84.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
315  99.0   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
316  37.0  29.0  24.0  22.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     wk74  wk75  wk76  
0     NaN   NaN   NaN  
1     NaN   NaN   NaN  
2     NaN   NaN   NaN  
3     NaN   NaN   NaN  
4     NaN   NaN   NaN  
..    ...   ...   ...  
312   NaN   NaN   NaN  
313   NaN   NaN   NaN  
314   NaN   NaN   NaN  
315   NaN   NaN   NaN  
316   NaN   NaN   NaN  

[317 rows x 81 columns]

In [4]:
billboard_long=pd.melt(billboard, id_vars=['year','artist','track','time','date.entered'], var_name='week', value_name='rating')

In [5]:
billboard_long.shape

(24092, 7)

In [6]:
billboard_long.head()

year        artist                    track  time date.entered week  rating
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk1    87.0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   2000-09-02  wk1    91.0
2  2000  3 Doors Down               Kryptonite  3:53   2000-04-08  wk1    81.0
3  2000  3 Doors Down                    Loser  4:24   2000-10-21  wk1    76.0
4  2000      504 Boyz            Wobble Wobble  3:35   2000-04-15  wk1    57.0

In [8]:
#track 이 loser 를 모두 검색
billboard_long[billboard_long.track=='Loser'] 
#가끔 아티스트나 등등 오타가 있을 수가 있다. 일관성을 유지하는 측면에서 노래 제목에 대한 아티스트명을 묶어서 저장을 해주는게 관리하는 측면에서 좋다.
#중복되는 노래가 많다. 처리가 필요함

year        artist  track  time date.entered  week  rating
3      2000  3 Doors Down  Loser  4:24   2000-10-21   wk1    76.0
320    2000  3 Doors Down  Loser  4:24   2000-10-21   wk2    76.0
637    2000  3 Doors Down  Loser  4:24   2000-10-21   wk3    72.0
954    2000  3 Doors Down  Loser  4:24   2000-10-21   wk4    69.0
1271   2000  3 Doors Down  Loser  4:24   2000-10-21   wk5    67.0
...     ...           ...    ...   ...          ...   ...     ...
22510  2000  3 Doors Down  Loser  4:24   2000-10-21  wk72     NaN
22827  2000  3 Doors Down  Loser  4:24   2000-10-21  wk73     NaN
23144  2000  3 Doors Down  Loser  4:24   2000-10-21  wk74     NaN
23461  2000  3 Doors Down  Loser  4:24   2000-10-21  wk75     NaN
23778  2000  3 Doors Down  Loser  4:24   2000-10-21  wk76     NaN

[76 rows x 7 columns]

In [10]:
billboard_songs=billboard_long[['year','artist','track','time']]
billboard_songs

year            artist                    track  time
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22
1      2000           2Ge+her  The Hardest Part Of ...  3:15
2      2000      3 Doors Down               Kryptonite  3:53
3      2000      3 Doors Down                    Loser  4:24
4      2000          504 Boyz            Wobble Wobble  3:35
...     ...               ...                      ...   ...
24087  2000       Yankee Grey     Another Nine Minutes  3:10
24088  2000  Yearwood, Trisha          Real Live Woman  3:55
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19
24090  2000     Zombie Nation            Kernkraft 400  3:30
24091  2000   matchbox twenty                     Bent  4:12

[24092 rows x 4 columns]

In [12]:
#중복데이터 제거 billboard_songs
billboard_songs=billboard_songs.drop_duplicates()
billboard_songs.shape

(317, 4)

In [13]:
billboard_songs.head()

year        artist                    track  time
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22
1  2000       2Ge+her  The Hardest Part Of ...  3:15
2  2000  3 Doors Down               Kryptonite  3:53
3  2000  3 Doors Down                    Loser  4:24
4  2000      504 Boyz            Wobble Wobble  3:35

In [14]:
billboard_long

year            artist                    track  time date.entered  \
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08   
3      2000      3 Doors Down                    Loser  4:24   2000-10-21   
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   
...     ...               ...                      ...   ...          ...   
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating  
0       wk1    87.0  
1       wk1    91.0  
2       wk1    81.0  
3       wk1    76.0  
4       wk1    57.0  
...     ...     ...  
24087  wk76     NaN  
24088  wk76     NaN  
24089  wk76     NaN  
24090  wk76     NaN  
24091  wk76     NaN  

[24092 rows x 7 columns]

In [15]:
#billboard songs 에 아이디 컬럼 추가
billboard_songs['id']=range(len(billboard_songs))
billboard_songs.head() #id 열로 인하여 노래들 간에 구분이 가능해질것임

<ipython-input-15-2c10e817f720>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  billboard_songs['id']=range(len(billboard_songs))


year        artist                    track  time  id
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   1
2  2000  3 Doors Down               Kryptonite  3:53   2
3  2000  3 Doors Down                    Loser  4:24   3
4  2000      504 Boyz            Wobble Wobble  3:35   4

In [20]:
# billboard_long.merge(billboard_songs)
billboard_ratings=billboard_long.merge(billboard_songs, on=['year', 'artist', 'track', 'time'])
billboard_ratings.shape #7 -> 8개의 열이 된것을 알 수 있다. +id column

(24092, 8)

### <U>__배열 연결__</U>: 열 또는 행의 수가 동일한 배열을 연결: stack,  
                    vstack (v=vertical 열의 개수가 동일한: 행이증가),         y축  
                    hstack (h=horizontal 행의 개수가 동일한: 열이 증가), ...  x축  
                    dstack (d=depth 깊이 방향으로 함침) z축

In [26]:
#행의 수가 동일
np.ones((2,3)), np.zeros((2,2))

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.]]))

In [24]:
a1=np.ones((2,3))
a2=np.zeros((2,2))
#a1 과 a2는 행의 수가 동일 
# 넘파이 함수임
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [28]:
#열의 수가 동일
np.ones((2,3)), np.zeros((3,3))

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [27]:
a1=np.ones((2,3))
a2=np.zeros((3,3))
#a1 과 a2는 열의 수가 동일 
# 넘파이 함수임
np.vstack([a1, a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
#dstack :(depth) 방향으로 배열을 연결
# (3*4), (3*4) => dstack => (3*4*2) #2차원 배열 2개 연결하여 3차원 배열 1개 생성
a1=np.ones((3,4))
a2=np.zeros((3,4))
print(np.dstack([a1, a2]))
np.dstack([a1,a2]).shape #(3,4,2) == (행, 열, 깊이)


[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


(3, 4, 2)

In [33]:
# stack 함수는 dstack의 기능을 확장, dstack 은 마지막 차원으로 연결
# stack은 사용자가 지정한 축으로 배열을 연결 (axis=0, 디폴트, 가장 앞쪽에 차원이 추가)

a1.shape #3,4
a2.shape #3,4
a=np.stack([a1, a2])
print(a)
print(a.shape) #depth 가 4

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)


In [37]:
a1.shape #3,4
a2.shape #3,4
a00=np.stack([a1,a2]) #default: axis=0
print(a00)
print(a00.shape) #depth 가 4
print('='*50)
a01=np.stack([a1,a2], axis=1)
print(a01)
print(a01.shape) #depth 가 4
print('='*50)
a02=np.stack([a1,a2], axis=2)
print(a02)
print(a02.shape) #depth 가 4
print('='*50)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]
(3, 2, 4)
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
(3, 4, 2)


In [39]:
#hstack 하고 비슷하지만, 두 배열을 좌우로 연결
np.r_[np.array([1,2,3]), np.array([4,5,6])] #array([1, 2, 3, 4, 5, 6])   1차원


#차원을 증가시킨 후 좌우로 연결
np.c_[np.array([1,2,3]), np.array([4,5,6])] #array([[1, 4],
                                           #        [2, 5],
                                           #        [3, 6]])  2차원

#         밑줄은 인덱서 이지만 대괄호가 붙는 함수를 인덱서 라고 부름

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
# tile: 동일한 배열을 반복해서 연결
a=np.array([[0,1,2], 
            [3,4,5]])
np.tile(a,2)
# array([[0, 1, 2, 0, 1, 2],
#        [3, 4, 5, 3, 4, 5]])

np.tile(a, (3,2))
# 2행 3열의 배열을 -> 타일(3,2) -> 6행6열 배열 생성  (2*3, 3*2) -> (6,6)
# array([[0, 1, 2, 0, 1, 2],
#        [3, 4, 5, 3, 4, 5],
#        [0, 1, 2, 0, 1, 2],
#        [3, 4, 5, 3, 4, 5],
#        [0, 1, 2, 0, 1, 2],
#        [3, 4, 5, 3, 4, 5]])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### 핵심  
데이터프레임 인덱스 조작 (설정 / 제거)  
set_index: __기존 행 인덱스를 제거 하고, 데이터 컬럼 중 어느 하나를 인덱스로 설정__  
reset_index: __기존 행 인덱스를 제거하고, 인덱스를 데이터 열로 추가__  
  

In [46]:
myList=list("ABCDE") #['A', 'B', 'C', 'D', 'E'] 요소가 5개

# rand함수: 0<=~<1 사이 의 난수를 생성
myArr=np.round(np.random.rand(3,5),2) #3행 5열 난수 배열 생성 , np.round( ,2) 는 소수이하 2째자리

In [51]:
#myList 와 myArr을 연결, 위아래로 연결 (vstack)
np.vstack([myList, myArr])

df1=pd.DataFrame(np.vstack([myList, myArr]).T,
                 columns=['C1','C2','C3','C4']) #(5,4)
df1

C1    C2    C3    C4
0  A  0.87  0.89  0.26
1  B  0.36  0.51  0.01
2  C  0.47  0.26  0.32
3  D   0.6  0.03  0.74
4  E  0.22   0.9  0.52

In [56]:
#set_index 는 데이터프레임에 속함
df2=df1.set_index(['C1'])
df2

C2    C3    C4
C1                  
A   0.87  0.89  0.26
B   0.36  0.51  0.01
C   0.47  0.26  0.32
D    0.6  0.03  0.74
E   0.22   0.9  0.52

In [64]:
#df2에서 C2열을 행 인덱스로 지정
df2.set_index(['C2']) #기존 인덱스가 지워짐

C3    C4
C2              
0.87  0.89  0.26
0.36  0.51  0.01
0.47  0.26  0.32
0.6   0.03  0.74
0.22   0.9  0.52

In [68]:
#df2에서 C2열을 행 인덱스로 지정
#기존 행 인덱스를 제거하고, 인덱스를 데이터 열로 추가 (reset_index)
df2
df2.reset_index()

C1    C2    C3    C4
0  A  0.87  0.89  0.26
1  B  0.36  0.51  0.01
2  C  0.47  0.26  0.32
3  D   0.6  0.03  0.74
4  E  0.22   0.9  0.52

In [69]:
# reset_index를 하는데 다시 못돌아오게 하려면
df2.reset_index(drop=True)

C2    C3    C4
0  0.87  0.89  0.26
1  0.36  0.51  0.01
2  0.47  0.26  0.32
3   0.6  0.03  0.74
4  0.22   0.9  0.52

In [70]:
#다중인덱스
# 데이터프레임의 columns 인수를 행렬로 주게되면 다중 인덱스
pd.DataFrame(np.random.randn(5,4))

# 열 인덱스 
# 0 1 2 3
# 을
# 아래와 같이 변경
# A         B
# C1   C2   C3   C4

0         1         2         3
0 -2.656623 -0.108627  0.498184  1.284468
1  1.156522 -0.113264 -0.692195  0.199306
2 -1.114700  0.671528  0.460410 -0.090112
3 -0.461752  1.837483 -0.278247 -0.377728
4 -0.033596  0.469434 -2.280002 -0.584853

In [73]:
#stack (위/아래)
#unstack (좌/우)

# 튜플로 부터 가져온 데이터로 다중인덱스를 만듬
mulIndex=pd.MultiIndex.from_tuples([('A', 'C1'),('A', 'C2'),
                                   ('B', 'C3'),('B', 'C4')])
mulIndex #다중 인덱스를 반드는 법

MultiIndex([('A', 'C1'),
            ('A', 'C2'),
            ('B', 'C3'),
            ('B', 'C4')],
           )

In [79]:
data=pd.DataFrame(np.random.randn(5,4),
                columns=mulIndex)
data

A                   B          
         C1        C2        C3        C4
0 -0.732933 -0.153409  0.454439  1.245019
1  0.717464 -0.111635  1.369168 -0.330733
2 -2.214466 -0.464850 -1.016171 -0.184838
3  0.225082 -0.399437  1.621539 -1.685173
4 -1.278529  0.901803 -0.469308 -0.748210

In [80]:
df3=pd.DataFrame(np.random.randn(5,4),
                columns=[['A','A','B','B'],
                        ['C1','C2','C3','C4']]) #list 의 list 속성을 주면 = multiIndex
df3

A                   B          
         C1        C2        C3        C4
0 -0.517073  0.702280  2.230755 -0.840536
1  0.708582 -0.907548 -0.041198 -1.172318
2 -0.645913  0.509567 -0.352932 -1.672937
3 -1.303394  0.823598  0.650849 -1.363818
4  0.770689 -1.286423  0.777992  0.863368

In [81]:
df3.columns #다중인덱스 이기때문에 MultiIndex

MultiIndex([('A', 'C1'),
            ('A', 'C2'),
            ('B', 'C3'),
            ('B', 'C4')],
           )

In [82]:
df3.columns.names=['Cidx1','Cidx2']
df3 #각각의 행에대한 이름

Cidx1         A                   B          
Cidx2        C1        C2        C3        C4
0     -0.517073  0.702280  2.230755 -0.840536
1      0.708582 -0.907548 -0.041198 -1.172318
2     -0.645913  0.509567 -0.352932 -1.672937
3     -1.303394  0.823598  0.650849 -1.363818
4      0.770689 -1.286423  0.777992  0.863368

In [90]:
df4=pd.DataFrame(np.random.randn(6,4),
            index=[['M','M','M','F','F','F'],
                   ['id1','id2','id3','id4','id5','id6']],
            columns=[['A','A','B','B'],
                    ['C','D','C','D']])
df4.index.names=['ridx1','ridx2']
df4.columns.names=['cidx1','cidx2']

In [91]:
df4

cidx1               A                   B          
cidx2               C         D         C         D
ridx1 ridx2                                        
M     id1   -0.610778  0.926745 -1.007973 -0.775167
      id2    0.540683  0.627408 -0.046439  0.946536
      id3    0.511267 -0.206610  0.226681  1.479338
F     id4    0.543580 -0.131449  0.293924 -1.847598
      id5    0.432453 -0.820516  1.545227  0.852569
      id6    0.322543  1.432328  0.638606  0.789840

In [96]:
# list comprehension
df4=pd.DataFrame(np.random.randn(6,4),
            index=[['M','M','M','F','F','F'],
                   ["id"+str(i+1) for i in range(3)]*2],
            columns=[['A','A','B','B'],
                    ['C','D','C','D']])
df4.index.names=['ridx1','ridx2']
df4.columns.names=['cidx1','cidx2']

In [97]:
df4

cidx1               A                   B          
cidx2               C         D         C         D
ridx1 ridx2                                        
M     id1   -1.082374 -1.444603  0.715130  1.551759
      id2    0.194552 -1.388439  0.196374 -0.121730
      id3    0.051273  0.338861  0.657145 -1.529059
F     id1    0.368377  1.283725  0.807125  0.636777
      id2    1.656995  0.169900 -0.141737  0.887665
      id3   -0.950074  0.633404 -0.064737 -1.144801

In [102]:
#stack(): 열 인덱스 -> 행 인덱스 쪽으로 오는데, 반시계 뱡항으로 90도 회전
# vice versa
#stack(): 행 인덱스 -> 열 인덱스 쪽으로 오는데, 시계 뱡항으로 90도 회전

#cidx1에 해당되는 열 인덱스가 (A, B) 행 인덱스로 지정
df4.stack("cidx1") #이름을 주면 이름에 해당하는 index가 이동한다.

cidx2                     C         D
ridx1 ridx2 cidx1                    
M     id1   A     -1.082374 -1.444603
            B      0.715130  1.551759
      id2   A      0.194552 -1.388439
            B      0.196374 -0.121730
      id3   A      0.051273  0.338861
            B      0.657145 -1.529059
F     id1   A      0.368377  1.283725
            B      0.807125  0.636777
      id2   A      1.656995  0.169900
            B     -0.141737  0.887665
      id3   A     -0.950074  0.633404
            B     -0.064737 -1.144801

In [101]:
df4.stack("cidx2")

cidx1                     A         B
ridx1 ridx2 cidx2                    
M     id1   C     -1.082374  0.715130
            D     -1.444603  1.551759
      id2   C      0.194552  0.196374
            D     -1.388439 -0.121730
      id3   C      0.051273  0.657145
            D      0.338861 -1.529059
F     id1   C      0.368377  0.807125
            D      1.283725  0.636777
      id2   C      1.656995 -0.141737
            D      0.169900  0.887665
      id3   C     -0.950074 -0.064737
            D      0.633404 -1.144801

In [103]:
df4.stack(1) #햇갈리니, 이름을 주는게 편하다

cidx1                     A         B
ridx1 ridx2 cidx2                    
M     id1   C     -1.082374  0.715130
            D     -1.444603  1.551759
      id2   C      0.194552  0.196374
            D     -1.388439 -0.121730
      id3   C      0.051273  0.657145
            D      0.338861 -1.529059
F     id1   C      0.368377  0.807125
            D      1.283725  0.636777
      id2   C      1.656995 -0.141737
            D      0.169900  0.887665
      id3   C     -0.950074 -0.064737
            D      0.633404 -1.144801

In [104]:
df4

cidx1               A                   B          
cidx2               C         D         C         D
ridx1 ridx2                                        
M     id1   -1.082374 -1.444603  0.715130  1.551759
      id2    0.194552 -1.388439  0.196374 -0.121730
      id3    0.051273  0.338861  0.657145 -1.529059
F     id1    0.368377  1.283725  0.807125  0.636777
      id2    1.656995  0.169900 -0.141737  0.887665
      id3   -0.950074  0.633404 -0.064737 -1.144801

In [106]:
df4.unstack("ridx1") #df4.unstack(0)

cidx1         A                                       B                      \
cidx2         C                   D                   C                   D   
ridx1         F         M         F         M         F         M         F   
ridx2                                                                         
id1    0.368377 -1.082374  1.283725 -1.444603  0.807125  0.715130  0.636777   
id2    1.656995  0.194552  0.169900 -1.388439 -0.141737  0.196374  0.887665   
id3   -0.950074  0.051273  0.633404  0.338861 -0.064737  0.657145 -1.144801   

cidx1            
cidx2            
ridx1         M  
ridx2            
id1    1.551759  
id2   -0.121730  
id3   -1.529059

In [107]:
df4.unstack("ridx2") #df4.unstack(1)

cidx1         A                                                           B  \
cidx2         C                             D                             C   
ridx2       id1       id2       id3       id1       id2       id3       id1   
ridx1                                                                         
F      0.368377  1.656995 -0.950074  1.283725  0.169900  0.633404  0.807125   
M     -1.082374  0.194552  0.051273 -1.444603 -1.388439  0.338861  0.715130   

cidx1                                                    
cidx2                             D                      
ridx2       id2       id3       id1       id2       id3  
ridx1                                                    
F     -0.141737 -0.064737  0.636777  0.887665 -1.144801  
M      0.196374  0.657145  1.551759 -0.121730 -1.529059