In [1]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [2]:
text=['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']

In [3]:
vocab = {} # 파이썬의 dictionary 자료형
sentences = []
stop_words = set(stopwords.words('english'))

for i in text:
    sentence = word_tokenize(i) # 단어 토큰화를 수행합니다.
    result = []

    for word in sentence: 
        word = word.lower() # 모든 단어를 소문자화하여 단어의 개수를 줄입니다.
        if word not in stop_words: # 단어 토큰화 된 결과에 대해서 불용어를 제거합니다.
            if len(word) > 2: # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거합니다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1
    sentences.append(result) 
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [4]:
print(vocab)

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [5]:
#빈도수 기준으로 내림차순 정렬
#sorted
vocab.items() # items()함수가 딕셔너리의 내용을 튜플 형식으로 묶어준다.

dict_items([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])

In [15]:
sorted(vocab.items()) #키를 기준으로 오름차순 정렬
sorted(vocab.items(), reverse=True)

[('word', 2),
 ('went', 1),
 ('secret', 6),
 ('person', 3),
 ('mountain', 1),
 ('knew', 1),
 ('kept', 4),
 ('keeping', 2),
 ('huge', 5),
 ('good', 1),
 ('driving', 1),
 ('crazy', 1),
 ('barber', 8)]

In [18]:
#키가 아니라 수치값을 기준으로 정렬하고 싶은경우 직접 키를 지정해주어야 한다.
vocab_sorted = sorted(vocab.items(), reverse=True, key=lambda x: x[1]) 
vocab_sorted
# key:정렬 기준, x에는 튜플이 전달됨, 키를 수치값으로 지정

[('barber', 8),
 ('secret', 6),
 ('huge', 5),
 ('kept', 4),
 ('person', 3),
 ('word', 2),
 ('keeping', 2),
 ('good', 1),
 ('knew', 1),
 ('driving', 1),
 ('crazy', 1),
 ('went', 1),
 ('mountain', 1)]

In [19]:
#가장 빈도수가 높은 단어들부터 인덱스가 순차적으로 부여
word_to_index = {}
i=0
for (word, freq) in vocab_sorted:
    if freq>1:
        i+=1
        word_to_index[word]=i
print(word_to_index) #가장 빈도수가 높은 단어들부터 인덱스가 순차적으로 부여됨

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [48]:
#빈도수가 가장 높은 vs개 단어 추출
vs = 5
# vs개 만큼의 단어들만 추출
[w[0] for w in word_to_index.items() if w[1] <= vs] #이 방법이 좋다.

['barber', 'secret', 'huge', 'kept', 'person']

In [51]:
# 인덱스가 5를 넘는 단어 제거
words_freq=[w for w, c in word_to_index.items() if c>vs]
words_freq
# vs개 만큼의 단어들만 추출

['word', 'keeping']

In [53]:
for w in words_freq:
    del(word_to_index[w])
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [56]:
sentences #워드 토큰화가 되어진 문장
#안에 단어들을 word_to_index 의 인덱스 값과 매칭시켜서 숫자로 변환
#sentences(자연어처리대상 텍스트)의 단어 중에서 word_to_index(코퍼스, Vocabulary)에 없는 단어는 OOV(Out Of Vocab.)
word_to_index['OOV']=len(word_to_index)+1 #인코딩 전에 설정

In [57]:
word_to_index

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}

In [58]:
sentences #아래 구조는 유지하고 모두 숫자로 변경

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [66]:
encoded=[]
for s in sentences:
    temp=[]
    for w in s:
        try:
            temp.append(word_to_index[w])
        except KeyError:  # <- 에러의 제목 발생시 아래것을 수행
            temp.append(word_to_index['OOV']) 
    encoded.append(temp)

In [67]:
encoded

[[1, 5],
 [1, 6, 5],
 [1, 3, 5],
 [6, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [6, 6, 3, 2, 6, 1, 6],
 [1, 6, 3, 6]]

패딩: 
- 위 encoded에서 가장 길이가긴 [6, 6, 3, 2, 6, 1, 6] = 7 을 찾은후에 나머지 모든 리스트의 길이를 동일하게(7) 맞추는 작업
- 동일한 크기로 해야하는 이유: 딥러닝 네트워크를 만들때, 구조를 동일하게 만들어 주는 작업이 필요!

In [73]:
#함수를 활용하는 방법:
from collections import Counter
import numpy as np

In [69]:
sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [70]:
words = [] #에 sentences데이터를 1차원으로 저장
for li in sentences:
    for word in li:
        words.append(word)

In [80]:
words=np.hstack(sentences) #스텍함수 사용
print(words)

['barber' 'person' 'barber' 'good' 'person' 'barber' 'huge' 'person'
 'knew' 'secret' 'secret' 'kept' 'huge' 'secret' 'huge' 'secret' 'barber'
 'kept' 'word' 'barber' 'kept' 'word' 'barber' 'kept' 'secret' 'keeping'
 'keeping' 'huge' 'secret' 'driving' 'barber' 'crazy' 'barber' 'went'
 'huge' 'mountain']


In [79]:
words=sum(sentences,[])
print(words)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


___
# 함수를 활용해서 작업

In [89]:
vocab=Counter(words)

In [90]:
print(vocab['barber'])

8


In [91]:
vs=5
vocab=vocab.most_common(vs) #가장 빈도가 높은 순서대로 정렬 + top5
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [94]:
i=0
word_to_index={}
for (w, f) in vocab:
    i+=1
    word_to_index[w]=i
    
word_to_index['OOV']=len(word_to_index)+1
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


ex) 법령코퍼스 = {'헌법':1, '피고인':2,....., 'OOV':1000}  
OOV : 자연어, 물, 컵 (__특정 코퍼스와 관련되지 않는 단어들__)

In [95]:
from nltk import FreqDist

In [97]:
vocab=FreqDist(np.hstack(sentences))
vocab
vocab['barber']

8

In [100]:
vocab=vocab.most_common(vs)

In [105]:
{w[0] : i+1 for i, w in enumerate (vocab)} #dictionary 컴프리핸션

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

### 패딩
- 문장의 길이를 가장 긴문장과 동일하게

In [106]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [107]:
sentences

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [108]:
tokenizer=Tokenizer()

In [109]:
tokenizer.fit_on_texts(sentences)

In [111]:
encoded=tokenizer.texts_to_sequences(sentences)
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [121]:
#가장 긴 길이를 출력 : 7
max_len=max([len(i) for i in encoded])
max_len

7

In [122]:
#한가지 방법을 정하기. 
#좌측 패딩, 우측 패딩
#오른쪽패딩일 경우 0이 오른쪽으로 채워짐 : [1, 5, 0, 0, 0, 0, 0]
#주로 우측을 많이 사용함. 이유: RNN할때 왼쪽부터 읽음
for item in encoded:
    while len(item)<max_len:
        item.append(0)
print(encoded)

[[1, 5, 0, 0, 0, 0, 0], [1, 8, 5, 0, 0, 0, 0], [1, 3, 5, 0, 0, 0, 0], [9, 2, 0, 0, 0, 0, 0], [2, 4, 3, 2, 0, 0, 0], [3, 2, 0, 0, 0, 0, 0], [1, 4, 6, 0, 0, 0, 0], [1, 4, 6, 0, 0, 0, 0], [1, 4, 2, 0, 0, 0, 0], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13, 0, 0, 0]]


In [124]:
#오후 실습

# 패딩

In [165]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [166]:
encoded=tokenizer.texts_to_sequences(sentences)

In [167]:
pad_sequences(encoded)

pad_sequences(encoded, padding='post')

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [168]:
pad_sequences(encoded, padding='post', maxlen=5) #maxlen:문서의 최대 길이

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]], dtype=int32)

In [169]:
pad_sequences(encoded, padding='post', maxlen=5, value=14) #maxlen:문서의 최대 길이

array([[ 1,  5, 14, 14, 14],
       [ 1,  8,  5, 14, 14],
       [ 1,  3,  5, 14, 14],
       [ 9,  2, 14, 14, 14],
       [ 2,  4,  3,  2, 14],
       [ 3,  2, 14, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  2, 14, 14],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14]], dtype=int32)

# 원핫인코딩

- run, runs가 의미는 같은데 다른 단어로 인식된다.
- 그러므로 원핫 인코딩을 하기전에는 단어집합이 만들어져 있어야한다.
- 단어집합 (자연어, 처리, 파이썬,...) -> 정수인코딩(1,2,3,...) -> 원핫인코딩(단어 집합 크기를 벡터의 차원으로 간주)
- 10차원 벡터 (단어가 10개, 인덱스: 1~10번 까지)에서 해당 단어의 위치에는 1을 주고, 나머지에는 0을 주는 방식으로 단어를 벡터 형태로 표현하게 됨.
```
자연어:1, 처리:2, 파이썬:3, .... 물:10  
자연어  -> 10000000000  
처리   -> 0100000000  
파이썬  -> 0010000000  
...  
물     -> 0000000001  
```

In [125]:
from konlpy.tag import Okt 

In [127]:
#Okt 객체를 생성
okt = Okt()
token = okt.morphs("나는 자연어 처리를 배운다") #형태소 분석
print(token) #나누어진 단어의 형태 = 토큰

['나', '는', '자연어', '처리', '를', '배운다']


In [128]:
# {나: 0,..., 배운다: 5}
word2index={}
for v in token:
    if v not in word2index.keys():
        word2index[v]=len(word2index)
print(word2index)

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [150]:
def ohe(word, word2index):
    n=word2index[word] #2
    encode_init=np.zeros(len(word2index))
    encode_init[n] = 1
    return encode_init.astype("int")

In [151]:
print(ohe("자연어", word2index)) #인덱스는 2일때 자연어: 00100 로 결과를 리턴하기

[0 0 1 0 0 0]


In [152]:
# 선생님
def ohe(word, word2index):
    ohv=[0]*len(word2index)
    idx=word2index[word]
    ohv[idx]=1
    return ohv

In [153]:
print(ohe("자연어", word2index))

[0, 0, 1, 0, 0, 0]


In [154]:
text = "나랑 코엑스에 브로슈어 가지러 갈래 갈래 갈래 브로슈어 가지러 가자"

In [155]:
from tensorflow.keras.utils import to_categorical

In [156]:
tok=Tokenizer()
tok
tok.fit_on_texts([text])

In [157]:
tok.index_word

{1: '갈래', 2: '브로슈어', 3: '가지러', 4: '나랑', 5: '코엑스에', 6: '가자'}

In [158]:
tok.word_index #단어집합

{'갈래': 1, '브로슈어': 2, '가지러': 3, '나랑': 4, '코엑스에': 5, '가자': 6}

In [159]:
text2="코엑스에 갈래 브로슈어 가지러 함께 가자 어서"

In [163]:
encoded=tok.texts_to_sequences([text2])[0] #정수 인코딩
encoded

[5, 1, 2, 3, 6]

In [164]:
#OneHot encoding
oh=to_categorical(encoded) 
oh

array([[0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

### 원핫인코딩의 한계:
- 단어의 개수가 많아지면 많아질수록 벡터의 차원이 늘어남 (부담스럽다) : 단어의 개수 = 벡터차원 개수
- 메모리 관점에서는 효율이 매우 떨어진다.
- 유사도 구하기가 어렵다.

```
국어=[1000]
수학=[0100]
과학=[0010]
영어=[0001]
4차원 벡터
여기서 유사도를 찾기가 매우 어렵다.

ex) 검색어 : 제주도 숙박(숙식, 호텔, 모텔, 게스트하우스, 잠잘곳,... <매우 많은 표현>)
연관검색 엔진을 원핫으로 만들면 썩 좋지 않다.
```
- 이런 문제를 해결하기 위해서는 단어들이 가지고 있는 의미를 반영해서 벡터화 진행
    - 단어의 의미를 부여하여 벡터화 (word2vec, fasttext(요즘 사용트렌드), lsa, lda...)
        - 자연어 처리를 rnn 을 넘어가서 배우면 fasttext

***
### 언어 모델?
- 단어의 순서에 확률을 적용한 모델
    - 통계적 기법 (ex: 베이지안)
        - 이전 단어 등장시 다음 단어를 예측
    - 신경망 기법 (ex-> LSTM, BERT)
        - 이전 단어와 다음 단어로부터 현재 단어를 예측(BERT)
        - 통계적 기법보다 성능이 더 좋다. 
        - (BERT이용해서 프로젝트 진행시 논문급)
        - ex) 코로나 ??? 결과가 음성입니다  (??? => 검사) 예측결과 

- 어느정도 내공이 쌓이면 논문을 봐야한다. 책에는 더이상 없다..

***

#### 통계적 기법:
```
번역: 
- 먹는다가 나올 확률이 마신다 보다 크다.
P(나는 밥을 먹는다) >> P(나는 밥을 마신다)

- 손님~ 커피가
P(나왔습니다) >> P(나오셨습니다)
: "손님~ 커피가 나왔습니다"

- 두문장중 더 확률이 높은 문장?
나는 밥을 먹습니다. (50%)
나는 날을 먹습니다. (10%)
나는 달을 먹습니다. (0.5%)


단어(w), 시퀀스(W) 단어가 순서대로 나열
다어가 n개, n개 나어가 단어-시퀀스 w 를 보일 확률

*다음단어 예측 확률*
n-1개 단어가 주어짐,
n번째 단어는 무엇이 올까?
p(Wn|W1,W2,...Wn-1)

*전체단어 시퀀스 w의 확률?
p(W) = n(pi)i=1 * (Wn|W1,...,Wn-1)


P(B|A) = P(A,B) / P(A)
P(A,B) = P(A) * P(B|A)

P(A,B,C,D) = P(A)*P(B|A) * P(C|A,B) * P(D|A,B,C)
P(X1,...,Xn) = P(X1)... ... P(Xn|X1...Xn-1)

P("An adorable little boy is spreading smiles") = 문장이 될 확률

- 문장의 확률? 이전 단어가 왔을때 다음 단어로 등장할 확률
- P(A|B) = 사건 B가 발생했을때 A가 나올 확률

- an이 나올 확률 * an이라는 단어가 나왔을때 그 다음단어로 adorable이 나올확률... 연쇄적으로 확률 계산: 
- P(An) * P(adorable|An) * P(little|An adorable) *...* P(smiles|An adorable little boy is spreading)

카운트기반 문장 확률
P(is | An adorable little boy) =? 
```
$$ count(An\;adorable\;little\;boy\;is) \over count(An\;adorable\;little\;boy) $$
- count(An adorable little boy) => 전체 문장에서 이 문장이 나온 수

###### N-gram 언어 모델
- n개 만큼의 단어들을 참조해서 그 다음단어가 무엇이 나올지 예상
- n => 1,2,3,4... 여러개의 숫자가 올수 있다.
    - n=1 <- 유니그램
    - n=2 <- 바이그램
    - n=3 <- 트라이그램
        - 일반적으로 바이그램, 트리아그램이 많이 사용된다 (논문 4이하).
        - 신경망에서 word2vec할때 나온다.
- ex) "An adorable little boy is spreading" + "???"(예상)
$$ P(w|boy\;is\;spreading) = count(boy\;is\;spreading\;w) \over count(boy\;is\;spreading) $$






#### 신경망 기법:
- 

___
- rnn 개선: GRU(조경현교수님 개발), LSTM

### Bag of Words (BOW)
- 단어 출현 순서 고려 X
- 빈도수 기반 단어 표현
    1. 문서의 모든 단어 추출 -> index
    2. 단어의 등장 횟수 표현

n-gram 유사도 문제
> ex:  
`문장1`: 오늘 강남에서 맛있는 된장찌개를 먹었다.  
`문장2`: 강남에서 먹었던 오늘의 된장찌개는 맛있었다.

- 2 gram유사도
    - 오늘/늘(공백)/(공백)강/강남/남에/에서/서(공백)/(공백)맛/맛있/.../었다.
    - 강남/남에/에서/.../었다.
    - 1번문장과 2번문장과 확률기반으로 접근하면 의미가 다르게 해석할수가 있어서 n-gram으로 접근
    - 1번문장과 2번문장을 2gram으로 나누었더니 나누어진 조각의 개수가 다를수 있다.
        - 1번과 2번이 겹치는 조각은 ex)13조각일때
    - 그러면 1번이(50조각), 2번이(52)조각 일때, 작은것이 분모로 => 13/50 = 유사도
- 3 gram유사도
- 4 gram유사도

### N-gram (N= 2, 3, 4)

In [411]:
s1 = "오늘 강남에서 맛있는 된장찌개를 먹었다."
s2 = "강남에서 먹었던 오늘의 된장찌개는 맛있었다."

def grams(sentence,n):
    i=0
    temp=[]
    while i != len(sentence)-(n-1):
        temp.append(sentence[i:i+n])
        i+=1
    return temp

def s1_s2(n):
    temp_denominator=[]
    s1_Ngrams=grams(s1, n)
    s2_Ngrams=grams(s2, n)
    temp_denominator.append(len(s1_Ngrams))
    temp_denominator.append(len(s2_Ngrams))
    set1=set(s1_Ngrams)
    set2=set(s2_Ngrams)
    inter=len(set1&set2)
    denominator = min(temp_denominator) #낮은 개수의 조각을 선택
    similarity = inter/denominator
    return print("{} grams 유사도: {:.2f}%".format(n, similarity*100), "\n분자:",inter,"\n분모:",denominator,"\n",s1_Ngrams,"\n",s2_Ngrams,"\n","--"*20)

n = [2,3,4]
for i in n:
    s1_s2(i)

2 grams 유사도: 76.19% 
분자: 16 
분모: 21 
 ['오늘', '늘 ', ' 강', '강남', '남에', '에서', '서 ', ' 맛', '맛있', '있는', '는 ', ' 된', '된장', '장찌', '찌개', '개를', '를 ', ' 먹', '먹었', '었다', '다.'] 
 ['강남', '남에', '에서', '서 ', ' 먹', '먹었', '었던', '던 ', ' 오', '오늘', '늘의', '의 ', ' 된', '된장', '장찌', '찌개', '개는', '는 ', ' 맛', '맛있', '있었', '었다', '다.'] 
 ----------------------------------------
3 grams 유사도: 45.00% 
분자: 9 
분모: 20 
 ['오늘 ', '늘 강', ' 강남', '강남에', '남에서', '에서 ', '서 맛', ' 맛있', '맛있는', '있는 ', '는 된', ' 된장', '된장찌', '장찌개', '찌개를', '개를 ', '를 먹', ' 먹었', '먹었다', '었다.'] 
 ['강남에', '남에서', '에서 ', '서 먹', ' 먹었', '먹었던', '었던 ', '던 오', ' 오늘', '오늘의', '늘의 ', '의 된', ' 된장', '된장찌', '장찌개', '찌개는', '개는 ', '는 맛', ' 맛있', '맛있었', '있었다', '었다.'] 
 ----------------------------------------
4 grams 유사도: 21.05% 
분자: 4 
분모: 19 
 ['오늘 강', '늘 강남', ' 강남에', '강남에서', '남에서 ', '에서 맛', '서 맛있', ' 맛있는', '맛있는 ', '있는 된', '는 된장', ' 된장찌', '된장찌개', '장찌개를', '찌개를 ', '개를 먹', '를 먹었', ' 먹었다', '먹었다.'] 
 ['강남에서', '남에서 ', '에서 먹', '서 먹었', ' 먹었던', '먹었던 ', '었던 오', '던 오늘', ' 오늘의', '오늘의 ', 

___